export interface WalletProvider {
  code: string;
  name: string;
  type: "BANK" | "EWALLET" | "CASH" | "OTHER";
  category: string;
  color: string;
  logoBg: string;
  logoColor: string;
  shortName: string;
  iconType: "bank" | "wallet" | "cash" | "other";
}

export const WALLET_PROVIDERS: WalletProvider[] = [
  // ── Bank Indonesia ──
  {
    code: "bca",
    name: "Bank Central Asia (BCA)",
    shortName: "BCA",
    type: "BANK",
    category: "Bank",
    color: "#00569c",
    logoBg: "#00569c",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "mandiri",
    name: "Bank Mandiri",
    shortName: "Mandiri",
    type: "BANK",
    category: "Bank",
    color: "#003d79",
    logoBg: "#003d79",
    logoColor: "#ffb700",
    iconType: "bank",
  },
  {
    code: "bri",
    name: "Bank Rakyat Indonesia (BRI)",
    shortName: "BRI",
    type: "BANK",
    category: "Bank",
    color: "#00529c",
    logoBg: "#00529c",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "bni",
    name: "Bank Negara Indonesia (BNI)",
    shortName: "BNI",
    type: "BANK",
    category: "Bank",
    color: "#e65300",
    logoBg: "#e65300",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "bsi",
    name: "Bank Syariah Indonesia (BSI)",
    shortName: "BSI",
    type: "BANK",
    category: "Bank",
    color: "#00a39d",
    logoBg: "#00a39d",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "jago",
    name: "Bank Jago",
    shortName: "Jago",
    type: "BANK",
    category: "Digital Bank",
    color: "#8a2be2",
    logoBg: "#5c2494",
    logoColor: "#fbbb00",
    iconType: "bank",
  },
  {
    code: "seabank",
    name: "SeaBank",
    shortName: "SeaBank",
    type: "BANK",
    category: "Digital Bank",
    color: "#ff5722",
    logoBg: "#ff5722",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "cimb",
    name: "CIMB Niaga",
    shortName: "CIMB",
    type: "BANK",
    category: "Bank",
    color: "#7e1616",
    logoBg: "#7e1616",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "permata",
    name: "Permata Bank",
    shortName: "Permata",
    type: "BANK",
    category: "Bank",
    color: "#008542",
    logoBg: "#008542",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "jenius",
    name: "Jenius (BTPN)",
    shortName: "Jenius",
    type: "BANK",
    category: "Digital Bank",
    color: "#009fe3",
    logoBg: "#009fe3",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "btn",
    name: "Bank Tabungan Negara (BTN)",
    shortName: "BTN",
    type: "BANK",
    category: "Bank",
    color: "#18458b",
    logoBg: "#18458b",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "danamon",
    name: "Bank Danamon",
    shortName: "Danamon",
    type: "BANK",
    category: "Bank",
    color: "#ff7f00",
    logoBg: "#ff7f00",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "panin",
    name: "Panin Bank",
    shortName: "Panin",
    type: "BANK",
    category: "Bank",
    color: "#008037",
    logoBg: "#008037",
    logoColor: "#ffffff",
    iconType: "bank",
  },
  {
    code: "ocbc",
    name: "OCBC NISP",
    shortName: "OCBC",
    type: "BANK",
    category: "Bank",
    color: "#e20613",
    logoBg: "#e20613",
    logoColor: "#ffffff",
    iconType: "bank",
  },

  // ── E-Wallet ──
  {
    code: "gopay",
    name: "GoPay",
    shortName: "GoPay",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#00aed6",
    logoBg: "#00aed6",
    logoColor: "#ffffff",
    iconType: "wallet",
  },
  {
    code: "ovo",
    name: "OVO",
    shortName: "OVO",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#4c2a86",
    logoBg: "#4c2a86",
    logoColor: "#ffffff",
    iconType: "wallet",
  },
  {
    code: "dana",
    name: "DANA",
    shortName: "DANA",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#118eea",
    logoBg: "#118eea",
    logoColor: "#ffffff",
    iconType: "wallet",
  },
  {
    code: "shopeepay",
    name: "ShopeePay",
    shortName: "ShopeePay",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#ee4d2d",
    logoBg: "#ee4d2d",
    logoColor: "#ffffff",
    iconType: "wallet",
  },
  {
    code: "linkaja",
    name: "LinkAja",
    shortName: "LinkAja",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#ed1c24",
    logoBg: "#ed1c24",
    logoColor: "#ffffff",
    iconType: "wallet",
  },
  {
    code: "astrapay",
    name: "AstraPay",
    shortName: "AstraPay",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#003c71",
    logoBg: "#003c71",
    logoColor: "#ffffff",
    iconType: "wallet",
  },
  {
    code: "isaku",
    name: "i.saku",
    shortName: "i.saku",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#005596",
    logoBg: "#005596",
    logoColor: "#ffcc00",
    iconType: "wallet",
  },
  {
    code: "paypal",
    name: "PayPal",
    shortName: "PayPal",
    type: "EWALLET",
    category: "E-Wallet",
    color: "#003087",
    logoBg: "#003087",
    logoColor: "#0079c1",
    iconType: "wallet",
  },

  // ── Tunai / Cash & Lainnya ──
  {
    code: "cash",
    name: "Uang Tunai (Cash)",
    shortName: "Tunai",
    type: "CASH",
    category: "Cash",
    color: "#16a34a",
    logoBg: "#16a34a",
    logoColor: "#ffffff",
    iconType: "cash",
  },
  {
    code: "brankas",
    name: "Brankas / Kas Kecil",
    shortName: "Kas Kecil",
    type: "CASH",
    category: "Cash",
    color: "#475569",
    logoBg: "#334155",
    logoColor: "#ffffff",
    iconType: "cash",
  },
  {
    code: "other",
    name: "Lainnya / Rekening Lain",
    shortName: "Lainnya",
    type: "OTHER",
    category: "Lainnya",
    color: "#6366f1",
    logoBg: "#4f46e5",
    logoColor: "#ffffff",
    iconType: "other",
  },
];

export function getWalletProvider(code?: string | null): WalletProvider {
  if (!code) return WALLET_PROVIDERS.find((p) => p.code === "cash")!;
  const found = WALLET_PROVIDERS.find((p) => p.code.toLowerCase() === code.toLowerCase());
  return found || {
    code: code.toLowerCase(),
    name: code.toUpperCase(),
    shortName: code.toUpperCase(),
    type: "OTHER",
    category: "Lainnya",
    color: "#64748b",
    logoBg: "#475569",
    logoColor: "#ffffff",
    iconType: "other",
  };
}
