"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Locale = "id" | "en";

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  locale: "id",
  setLocale: () => {},
  t: (key) => key,
});

const translations: Record<Locale, Record<string, string>> = {
  id: {
    // Sidebar
    "sidebar.ringkasan": "Ringkasan",
    "sidebar.transaksi": "Transaksi",
    "sidebar.kategori": "Kategori",
    "sidebar.laporan": "Laporan",
    "sidebar.pengaturan": "Pengaturan",
    "sidebar.anggota": "Anggota",
    "sidebar.penjualan": "Penjualan",
    "sidebar.laporanPenjualan": "Laporan Penjualan",
    "sidebar.langganan": "Langganan",
    "sidebar.riwayatOrder": "Riwayat Order",
    "sidebar.adminDashboard": "Admin Dashboard",
    "sidebar.sembunyikanSaldo": "Sembunyikan Saldo",
    "sidebar.tampilkanSaldo": "Tampilkan Saldo",
    "sidebar.modeTerang": "Mode Terang",
    "sidebar.modeGelap": "Mode Gelap",
    "sidebar.keluar": "Keluar",
    "sidebar.buatSekarang": "+ Buat sekarang",
    "sidebar.belumAdaWorkspace": "Belum ada workspace.",
    "sidebar.tambahWorkspace": "Tambah Workspace",
    "sidebar.perluasSidebar": "Perluas Sidebar",
    "sidebar.lang": "Bahasa",
    // Dashboard
    "greeting.morning": "Selamat Pagi",
    "greeting.afternoon": "Selamat Siang",
    "greeting.evening": "Selamat Sore",
    "greeting.night": "Selamat Malam",
    "greeting.friend": "teman",
    "dashboard.subtitle": "Berikut adalah ringkasan keuanganmu hari ini.",
    "dashboard.selectWorkspace": "Pilih workspace terlebih dahulu",
    "dashboard.selectWorkspaceDesc": "Buka daftar workspace dan pilih salah satu untuk melihat ringkasan keuangan.",
    "dashboard.viewWorkspace": "Lihat Workspace",
    "dashboard.netBalance": "Saldo Bersih (All-time)",
    "dashboard.totalIncome": "Total Pemasukan",
    "dashboard.totalExpense": "Total Pengeluaran",
    "dashboard.incomeThisMonth": "Pemasukan Bulan Ini",
    "dashboard.expenseThisMonth": "Pengeluaran Bulan Ini",
    "dashboard.netThisMonth": "Saldo Bersih Bulan Ini",
    "dashboard.lastMonth": "Bulan lalu",
    "dashboard.noIncomeThisMonth": "Belum ada pemasukan bulan ini",
    "dashboard.noExpenseThisMonth": "Belum ada pengeluaran bulan ini",
    "dashboard.incomeRemaining": "dari pemasukan tersisa",
    "dashboard.vsLastMonth": "vs bulan lalu",
    "dashboard.recentTransactions": "Transaksi Terbaru",
    "dashboard.viewAll": "Lihat semua",
    "dashboard.noTransactions": "Belum ada transaksi",
    "dashboard.recordFirstTransaction": "Catat transaksi pertama",
    "dashboard.last6Months": "6 Bulan Terakhir",
    "dashboard.pemasukan": "Pemasukan",
    "dashboard.pengeluaran": "Pengeluaran",
    "dashboard.noData": "Belum ada data",
    // Reports
    "reports.analytics": "Analitik",
    "reports.financialReport": "Laporan Keuangan",
    "reports.personalFinance": "Keuangan pribadi",
    "reports.selectDate": "Pilih tanggal (opsional)",
    "reports.thisMonth": "Bulan ini",
    "reports.vsLastMonth": "vs bln lalu",
    "reports.incomeVsExpense": "Pemasukan vs Pengeluaran",
    "reports.last6Months": "6 bulan terakhir",
    "reports.expenseByCategory": "Pengeluaran per Kategori",
    "reports.comparisonTitle": "Perbandingan Bulan Ini vs Bulan Lalu",
    "reports.metric": "Metrik",
    "reports.lastMonth": "Bulan Lalu",
    "reports.change": "Perubahan",
    "reports.date": "Tanggal",
    // Transactions
    "transactions.transactionsHeader": "Transaksi",
    "transactions.add": "Tambah",
    "transactions.allCategories": "Semua Kategori",
    "transactions.searchCategory": "Cari kategori...",
    "transactions.categoryNotFound": "Kategori tidak ditemukan",
    "transactions.allTypes": "Semua Tipe",
    "transactions.income": "Pemasukan",
    "transactions.expense": "Pengeluaran",
    "transactions.difference": "Selisih",
    "transactions.searchPlaceholder": "Cari catatan transaksi...",
    "transactions.filter": "Filter",
    "transactions.reset": "Reset",
    "transactions.type": "Tipe Transaksi",
    "transactions.category": "Kategori",
    "transactions.dateRange": "Rentang Tanggal",
    "transactions.from": "Dari",
    "transactions.to": "Sampai",
    "transactions.sort": "Urutkan",
    "transactions.newest": "Terbaru",
    "transactions.oldest": "Terlama",
    "transactions.highestAmount": "Nominal Terbesar",
    "transactions.lowestAmount": "Nominal Terkecil",
    "transactions.categoryAZ": "Kategori (A-Z)",
    "transactions.categoryZA": "Kategori (Z-A)",
    "transactions.dateHeader": "Tanggal",
    "transactions.typeHeader": "Tipe",
    "transactions.categoryHeader": "Kategori",
    "transactions.notesHeader": "Catatan",
    "transactions.amountHeader": "Nominal",
    "transactions.createdByHeader": "Dibuat oleh",
    "transactions.in": "Masuk",
    "transactions.out": "Keluar",
    "transactions.found": "transaksi ditemukan",
    "transactions.exporting": "Mengekspor...",
    "transactions.noTransactions": "Belum ada transaksi",
    "transactions.addNow": "Tambah sekarang",
    "transactions.pageOf": "Halaman",
    "transactions.of": "dari",
    "transactions.deleteTitle": "Hapus Transaksi?",
    "transactions.deleteText": "Transaksi ini akan dihapus permanen dan tidak bisa dikembalikan.",
    "transactions.yesDelete": "Ya, Hapus",
    "transactions.cancel": "Batal",
    "transactions.warning": "Perhatian",
    "transactions.verifyEmailText": "Kamu harus memverifikasi alamat emailmu terlebih dahulu sebelum bisa mencatat transaksi.",
    "transactions.understood": "Mengerti",
    // Categories
    "categories.management": "Manajemen",
    "categories.newCategory": "Kategori Baru",
    "categories.all": "Semua",
    "categories.close": "tutup",
    "categories.noCategories": "Belum ada kategori. Buat yang pertama!",
    "categories.default": "Bawaan",
    "categories.deleteTitle": "Hapus Kategori?",
    "categories.deleteText": "Apakah Anda yakin ingin menghapus kategori",
    "categories.failedDelete": "Gagal menghapus kategori",
    // Settings
    "settings.configuration": "Konfigurasi",
    "settings.title": "Pengaturan Workspace",
    "settings.subtitle": "Konfigurasi pengaturan workspace Anda secara menyeluruh.",
    "settings.info": "Informasi Workspace",
    "settings.name": "Nama Workspace",
    "settings.description": "Deskripsi",
    "settings.optional": "Opsional",
    "settings.currency": "Mata Uang",
    "settings.saved": "Pengaturan berhasil disimpan.",
    "settings.saveChanges": "Simpan Perubahan",
    "settings.dangerZone": "Zona Berbahaya",
    "settings.leaveTitle": "Keluar dari Workspace",
    "settings.leaveDesc": "Kamu tidak akan bisa lagi mengakses workspace ini.",
    "settings.leaveBtn": "Keluar",
    "settings.deleteTitle": "Hapus Workspace",
    "settings.deleteDesc": "Hapus workspace beserta semua transaksi dan anggota. Permanen.",
    "settings.deleteBtn": "Hapus",
    "settings.alertDeleteTitle": "Hapus Workspace?",
    "settings.alertDeleteText": "Apakah Anda yakin ingin menghapus workspace ini? Semua data transaksi dan anggota akan ikut <b>terhapus secara permanen</b>.",
    "settings.alertLeaveTitle": "Keluar Workspace?",
    "settings.alertLeaveText": "Apakah Anda yakin ingin keluar dari workspace ini? Anda tidak akan bisa mengakses data di dalamnya lagi.",
    "settings.yesLeave": "Ya, Keluar",
    // Members
    "members.collaboration": "Kolaborasi",
    "members.title": "Anggota Workspace",
    "members.subtitle": "Kelola anggota dan undangan untuk workspace Anda.",
    "members.invite": "Undang Anggota",
    "members.searchPlaceholder": "Cari nama atau email anggota baru...",
    "members.usersOnPlatform": "Pengguna di platform",
    "members.inviteBtn": "Undang",
    "members.shareDesc": "Bagikan link ini secara manual ke orang yang ingin kamu undang.",
    "members.copied": "Disalin!",
    "members.copyLink": "Salin Link",
    "members.membersList": "Anggota",
    "members.you": "Kamu",
    "members.removeBtn": "Keluarkan anggota",
    "members.pendingInvites": "Undangan Pending",
    "members.invitedBy": "Oleh",
    "members.validUntil": "Berlaku hingga",
    "members.resend": "Kirim ulang undangan",
    "members.cancelInvite": "Batalkan undangan",
    "members.alertRemoveTitle": "Keluarkan Anggota?",
    "members.alertRemoveText": "Apakah Anda yakin ingin mengeluarkan",
    "members.alertRemoveTextSuffix": "dari workspace ini?",
    "members.yesRemove": "Ya, Keluarkan",
    "members.alertCancelTitle": "Batalkan Undangan?",
    "members.alertCancelText": "Apakah Anda yakin ingin membatalkan undangan ini?",
    "members.yesCancel": "Ya, Batalkan",
    // Onboarding
    "onboarding.title1": "Pilih Tipe Workspace",
    "onboarding.title2": "Detail Workspace",
    "onboarding.desc1": "Pilih sesuai kebutuhanmu. Tipe tidak bisa diubah setelah workspace dibuat.",
    "onboarding.desc2": "Isi informasi dasar workspace kamu.",
    "onboarding.financeTitle": "Keuangan",
    "onboarding.financeDesc": "Catat pemasukan & pengeluaran. Cocok untuk keuangan pribadi, keluarga, atau tim.",
    "onboarding.salesTitle": "Penjualan",
    "onboarding.salesDesc": "Catat penjualan produk dengan HPP. Hitung omzet, laba kotor & laba bersih otomatis.",
    "onboarding.continue": "Lanjut",
    "onboarding.back": "Kembali",
    "onboarding.creating": "Membuat...",
    "onboarding.createWorkspace": "Buat Workspace",
    "onboarding.namePlaceholderSales": "Contoh: Toko Maju, Warung Sari...",
    "onboarding.namePlaceholderFinance": "Contoh: Keuangan Keluarga, Kas RT...",
    "onboarding.descPlaceholder": "Catatan singkat tentang workspace ini...",
    // Billing
    "billing.trialStatus": "Trial Aktif",
    "billing.activeStatus": "Aktif",
    "billing.expiredStatus": "Kadaluarsa",
    "billing.cancelledStatus": "Dibatalkan",
    "billing.title": "Billing & Langganan",
    "billing.subtitle": "Kelola paket langganan dan pembayaranmu.",
    "billing.currentPlan": "Paket Saat Ini",
    "billing.trialUntil": "Trial hingga",
    "billing.activeUntil": "Aktif hingga",
    "billing.cancel": "Batalkan",
    "billing.choosePlan": "Pilih Paket",
    "billing.perMonth": "/ bulan",
    "billing.activePlan": "✓ Paket Aktif",
    "billing.freeForever": "Gratis Selamanya",
    "billing.processing": "Memproses...",
    "billing.select": "Pilih",
    "billing.info": "Pembayaran diproses dengan aman melalui Midtrans. Kami tidak menyimpan data kartu kredit atau rekening bankmu.",
    "billing.unlimitedWorkspace": "Unlimited workspace",
    "billing.workspaceLimit": "workspace",
    "billing.unlimitedTx": "Unlimited transaksi",
    "billing.txLimit": "transaksi",
    "billing.unlimitedCategories": "Unlimited kategori custom",
    "billing.categoriesLimit": "kategori custom",
    "billing.reports": "Laporan & grafik lanjutan",
    "billing.budgeting": "Budgeting & notifikasi",
    "billing.cancelTitle": "Batalkan Langganan?",
    "billing.cancelText": "Kamu masih bisa menggunakan fitur premium hingga akhir periode ini.",
    "billing.yesCancel": "Ya, Batalkan",
    "billing.noCancel": "Tidak",
    "billing.syncTitle": "Menyiapkan Akun... ⏳",
    "billing.syncText": "Sedang mensinkronisasi data langgananmu.",
    "billing.successTitle": "Pembayaran Berhasil! 🎉",
    "billing.successText": "Langgananmu sudah aktif. Selamat menikmati fitur premium!",
    "billing.pendingTitle": "Menunggu Pembayaran",
    "billing.pendingText": "Kami akan mengaktifkan akunmu setelah pembayaran dikonfirmasi.",
    "billing.failedTitle": "Pembayaran Gagal",
    "billing.failedText": "Silakan coba kembali.",
  },
  en: {
    // Sidebar
    "sidebar.ringkasan": "Summary",
    "sidebar.transaksi": "Transactions",
    "sidebar.kategori": "Categories",
    "sidebar.laporan": "Reports",
    "sidebar.pengaturan": "Settings",
    "sidebar.anggota": "Members",
    "sidebar.penjualan": "Sales",
    "sidebar.laporanPenjualan": "Sales Reports",
    "sidebar.langganan": "Subscription",
    "sidebar.riwayatOrder": "Order History",
    "sidebar.adminDashboard": "Admin Dashboard",
    "sidebar.sembunyikanSaldo": "Hide Balance",
    "sidebar.tampilkanSaldo": "Show Balance",
    "sidebar.modeTerang": "Light Mode",
    "sidebar.modeGelap": "Dark Mode",
    "sidebar.keluar": "Logout",
    "sidebar.buatSekarang": "+ Create now",
    "sidebar.belumAdaWorkspace": "No workspaces found.",
    "sidebar.tambahWorkspace": "Add Workspace",
    "sidebar.perluasSidebar": "Expand Sidebar",
    "sidebar.lang": "Language",
    // Dashboard
    "greeting.morning": "Good Morning",
    "greeting.afternoon": "Good Afternoon",
    "greeting.evening": "Good Evening",
    "greeting.night": "Good Night",
    "greeting.friend": "friend",
    "dashboard.subtitle": "Here is your financial summary today.",
    "dashboard.selectWorkspace": "Please select a workspace",
    "dashboard.selectWorkspaceDesc": "Open the workspace list and select one to view the financial summary.",
    "dashboard.viewWorkspace": "View Workspaces",
    "dashboard.netBalance": "Net Balance (All-time)",
    "dashboard.totalIncome": "Total Income",
    "dashboard.totalExpense": "Total Expense",
    "dashboard.incomeThisMonth": "Income This Month",
    "dashboard.expenseThisMonth": "Expense This Month",
    "dashboard.netThisMonth": "Net Balance This Month",
    "dashboard.lastMonth": "Last month",
    "dashboard.noIncomeThisMonth": "No income this month",
    "dashboard.noExpenseThisMonth": "No expense this month",
    "dashboard.incomeRemaining": "of income remaining",
    "dashboard.vsLastMonth": "vs last month",
    "dashboard.recentTransactions": "Recent Transactions",
    "dashboard.viewAll": "View all",
    "dashboard.noTransactions": "No transactions found",
    "dashboard.recordFirstTransaction": "Record your first transaction",
    "dashboard.last6Months": "Last 6 Months",
    "dashboard.pemasukan": "Income",
    "dashboard.pengeluaran": "Expense",
    "dashboard.noData": "No data available",
    // Reports
    "reports.analytics": "Analytics",
    "reports.financialReport": "Financial Reports",
    "reports.personalFinance": "Personal finance",
    "reports.selectDate": "Select date (optional)",
    "reports.thisMonth": "This month",
    "reports.vsLastMonth": "vs last month",
    "reports.incomeVsExpense": "Income vs Expense",
    "reports.last6Months": "Last 6 months",
    "reports.expenseByCategory": "Expense by Category",
    "reports.comparisonTitle": "Comparison: This Month vs Last Month",
    "reports.metric": "Metric",
    "reports.lastMonth": "Last Month",
    "reports.change": "Change",
    "reports.date": "Date",
    // Transactions
    "transactions.transactionsHeader": "Transactions",
    "transactions.add": "Add",
    "transactions.allCategories": "All Categories",
    "transactions.searchCategory": "Search category...",
    "transactions.categoryNotFound": "Category not found",
    "transactions.allTypes": "All Types",
    "transactions.income": "Income",
    "transactions.expense": "Expense",
    "transactions.difference": "Difference",
    "transactions.searchPlaceholder": "Search transaction notes...",
    "transactions.filter": "Filter",
    "transactions.reset": "Reset",
    "transactions.type": "Transaction Type",
    "transactions.category": "Category",
    "transactions.dateRange": "Date Range",
    "transactions.from": "From",
    "transactions.to": "To",
    "transactions.sort": "Sort",
    "transactions.newest": "Newest",
    "transactions.oldest": "Oldest",
    "transactions.highestAmount": "Highest Amount",
    "transactions.lowestAmount": "Lowest Amount",
    "transactions.categoryAZ": "Category (A-Z)",
    "transactions.categoryZA": "Category (Z-A)",
    "transactions.dateHeader": "Date",
    "transactions.typeHeader": "Type",
    "transactions.categoryHeader": "Category",
    "transactions.notesHeader": "Notes",
    "transactions.amountHeader": "Amount",
    "transactions.createdByHeader": "Created by",
    "transactions.in": "In",
    "transactions.out": "Out",
    "transactions.found": "transactions found",
    "transactions.exporting": "Exporting...",
    "transactions.noTransactions": "No transactions found",
    "transactions.addNow": "Add now",
    "transactions.pageOf": "Page",
    "transactions.of": "of",
    "transactions.deleteTitle": "Delete Transaction?",
    "transactions.deleteText": "This transaction will be permanently deleted and cannot be undone.",
    "transactions.yesDelete": "Yes, Delete",
    "transactions.cancel": "Cancel",
    "transactions.warning": "Warning",
    "transactions.verifyEmailText": "You must verify your email address first before you can record transactions.",
    "transactions.understood": "Understood",
    // Categories
    "categories.management": "Management",
    "categories.newCategory": "New Category",
    "categories.all": "All",
    "categories.close": "close",
    "categories.noCategories": "No categories found. Create the first one!",
    "categories.default": "Default",
    "categories.deleteTitle": "Delete Category?",
    "categories.deleteText": "Are you sure you want to delete category",
    "categories.failedDelete": "Failed to delete category",
    // Settings
    "settings.configuration": "Configuration",
    "settings.title": "Workspace Settings",
    "settings.subtitle": "Configure your workspace settings thoroughly.",
    "settings.info": "Workspace Information",
    "settings.name": "Workspace Name",
    "settings.description": "Description",
    "settings.optional": "Optional",
    "settings.currency": "Currency",
    "settings.saved": "Settings saved successfully.",
    "settings.saveChanges": "Save Changes",
    "settings.dangerZone": "Danger Zone",
    "settings.leaveTitle": "Leave Workspace",
    "settings.leaveDesc": "You will no longer be able to access this workspace.",
    "settings.leaveBtn": "Leave",
    "settings.deleteTitle": "Delete Workspace",
    "settings.deleteDesc": "Delete workspace along with all transactions and members. Permanent.",
    "settings.deleteBtn": "Delete",
    "settings.alertDeleteTitle": "Delete Workspace?",
    "settings.alertDeleteText": "Are you sure you want to delete this workspace? All transaction data and members will be <b>permanently deleted</b>.",
    "settings.alertLeaveTitle": "Leave Workspace?",
    "settings.alertLeaveText": "Are you sure you want to leave this workspace? You will not be able to access the data inside it again.",
    "settings.yesLeave": "Yes, Leave",
    // Members
    "members.collaboration": "Collaboration",
    "members.title": "Workspace Members",
    "members.subtitle": "Manage members and invitations for your workspace.",
    "members.invite": "Invite Members",
    "members.searchPlaceholder": "Search name or email of new member...",
    "members.usersOnPlatform": "Users on platform",
    "members.inviteBtn": "Invite",
    "members.shareDesc": "Share this link manually with the person you want to invite.",
    "members.copied": "Copied!",
    "members.copyLink": "Copy Link",
    "members.membersList": "Members",
    "members.you": "You",
    "members.removeBtn": "Remove member",
    "members.pendingInvites": "Pending Invitations",
    "members.invitedBy": "By",
    "members.validUntil": "Valid until",
    "members.resend": "Resend invitation",
    "members.cancelInvite": "Cancel invitation",
    "members.alertRemoveTitle": "Remove Member?",
    "members.alertRemoveText": "Are you sure you want to remove",
    "members.alertRemoveTextSuffix": "from this workspace?",
    "members.yesRemove": "Yes, Remove",
    "members.alertCancelTitle": "Cancel Invitation?",
    "members.alertCancelText": "Are you sure you want to cancel this invitation?",
    "members.yesCancel": "Yes, Cancel",
    // Onboarding
    "onboarding.title1": "Choose Workspace Type",
    "onboarding.title2": "Workspace Details",
    "onboarding.desc1": "Choose according to your needs. Type cannot be changed after workspace is created.",
    "onboarding.desc2": "Fill in your workspace basic information.",
    "onboarding.financeTitle": "Finance",
    "onboarding.financeDesc": "Record income & expenses. Suitable for personal, family, or team finances.",
    "onboarding.salesTitle": "Sales",
    "onboarding.salesDesc": "Record product sales with COGS. Calculate revenue, gross profit & net profit automatically.",
    "onboarding.continue": "Continue",
    "onboarding.back": "Back",
    "onboarding.creating": "Creating...",
    "onboarding.createWorkspace": "Create Workspace",
    "onboarding.namePlaceholderSales": "e.g. Shop, Cafe, Store...",
    "onboarding.namePlaceholderFinance": "e.g. Personal Finance, Family, Club...",
    "onboarding.descPlaceholder": "A short note about this workspace...",
    // Billing
    "billing.trialStatus": "Trial Active",
    "billing.activeStatus": "Active",
    "billing.expiredStatus": "Expired",
    "billing.cancelledStatus": "Cancelled",
    "billing.title": "Billing & Subscription",
    "billing.subtitle": "Manage your subscription package and payments.",
    "billing.currentPlan": "Current Plan",
    "billing.trialUntil": "Trial until",
    "billing.activeUntil": "Active until",
    "billing.cancel": "Cancel",
    "billing.choosePlan": "Select Plan",
    "billing.perMonth": "/ month",
    "billing.activePlan": "✓ Active Plan",
    "billing.freeForever": "Free Forever",
    "billing.processing": "Processing...",
    "billing.select": "Choose",
    "billing.info": "Payments are processed securely via Midtrans. We do not store your credit card or bank account details.",
    "billing.unlimitedWorkspace": "Unlimited workspace",
    "billing.workspaceLimit": "workspace",
    "billing.unlimitedTx": "Unlimited transactions",
    "billing.txLimit": "transactions",
    "billing.unlimitedCategories": "Unlimited custom categories",
    "billing.categoriesLimit": "custom categories",
    "billing.reports": "Advanced reports & charts",
    "billing.budgeting": "Budgeting & notifications",
    "billing.cancelTitle": "Cancel Subscription?",
    "billing.cancelText": "You can still use premium features until the end of this period.",
    "billing.yesCancel": "Yes, Cancel",
    "billing.noCancel": "No",
    "billing.syncTitle": "Preparing Account... ⏳",
    "billing.syncText": "Synchronizing your subscription data.",
    "billing.successTitle": "Payment Successful! 🎉",
    "billing.successText": "Your subscription is now active. Enjoy premium features!",
    "billing.pendingTitle": "Waiting for Payment",
    "billing.pendingText": "We will activate your account after the payment is confirmed.",
    "billing.failedTitle": "Payment Failed",
    "billing.failedText": "Please try again.",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("id");

  useEffect(() => {
    const match = document.cookie.match(/(^| )locale=([^;]+)/);
    if (match && (match[2] === "id" || match[2] === "en")) {
      setLocaleState(match[2] as Locale);
    } else {
      const stored = localStorage.getItem("dwitku-locale");
      if (stored === "id" || stored === "en") {
        setLocaleState(stored as Locale);
      }
    }
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem("dwitku-locale", newLocale);
    document.cookie = `locale=${newLocale}; path=/; max-age=31536000`;
  };

  const t = (key: string): string => {
    return translations[locale][key] || translations["id"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
